#!/usr/bin/env bash
python MainMDLMLP.py
python MainMDLMLP.py
python MainMDLMLP.py
python MainMDLMLP.py
python MainMDLMLP.py
python MainMDLMLP.py
python MainMDLMLP.py
python MainMDLMLP.py
python MainMDLMLP.py
python MainMDLMLP.py
